#complementing a strand of DNA
#Josh Rudolph
#9/22/17

strand = "GGGCTACATCATTCATCCAGTCTTTACCACACTTGCGGGAGCTCATTGATTCACTTTAAAGCTGCCTGGCCCTATTGAGGAGTCCCCTCAGCGCTACTCCATCGGTTACAATAAGTTATGCGGCCCACAATAGGCAGTCTCTCCTCCGGCCGTTCGCCACTGCACTTTGCCGCGGGTGGGGCACCCAATAGGAATTGGAGATGGGTCCCAACGCTGTGCAACCCGACCAAGCTGGCGGTGCCACTGCGAGATATTATTCCTTCTTATTGCCTCTTCTCCCGATAGGTAAATGGATGCCAACGTATTTCTAACACACGAATTAAGCGTATCACAGTTTGAAGCAATGGTATGTTCGCTAACTTCTCTGCCCACGAATCTTCACCTATGAGTGCAGTACCTTCACTTCTGGCTCGTACTAAGTACCTAACCACTGTCGTTGTAGAGGCCGGGCCGTTCTCTAGGGGCCGCCCGCCTCCGATGGTACGCAGTTTCACCCAGGATGTGACCAACCGACAATCACATCTGGTCAGATAGTCTTTGCCCTCAGTCGTTGGTGGCTATGAGGAAAGGTCAAGCTAGCAGAAAGTCATTCTAAACCAATAAATTAAGGACGATCGCTCAACCACGGCATATTATTGTAATGGATCAATGACCATCAGGTAACCGGCGTAGTGATCCCTCACGTTCGCCAACATCTCACACTGGTACCGCTATGCGTTCATGATTACAACATTGTAGATTATCAGTGCCTTAGCTTGATTTTTCGTCAAGGACTAGTGTGCATTTGGGAGTATTCCTACGGTCGGTATGATCGTACGAGATCTGCCAGTAATAAATACTATTAGCCTCAGGCGTAGCGGA"
compl = []
for n in strand:
	if n == 'A':
		compl.append('T')
	elif n == 'C':
		compl.append('G')
	elif n == 'G': 
		compl.append('C')
	elif n == 'T':
		compl.append('A')

print(("".join(compl))[::-1])

