#counting DNA nucleotides
#Josh Rudolph
#9/22/17
 

A, C, G, T = 0, 0, 0, 0
string = "TTGTGGGTCGCATCCATCGCGACAGTTCCTCTTTTCGCCGGTCTAGCACAAGGGGTACCACTGTGCCTGTTGTTACGGAGAGCGGTAGAATTTTGGGCAGTAATTGCTTGGGAGAAGCATAAACTTTTTAGTAGTGACTACCCTGGACTCATGGCTGCAAGTAAGATACATTTCTCTATGTTCCACGTGTCGATTGGACAAGAATGTACCCGGCTCACTTTCGTGTATAGATTTGCGTTGCACCAAGGATCACGAGGAAATCGAGGTCATTTGACCGCTCAAAGAGAACATTACTCTGTCGCGTGCCGAAATCGCGGTGATTAGTGTCATTGCCGTGATGCCCCCAGTCGTTAAGGACCGGCCGCAAGAATCTTGCTAGCTACCCCATCCAATGCTATGAGGTCCGTGGAGGGCGACAGAAGGTCTACACAAGCGACGCCCACTCTAATCCTGCATGGTGCCTTCGAGTGTAGGGTCGTAGCCCACCTACCACCTGTCATGTAGCATATAATAGCAGCTTTAGCACGAATCAAGCGCTCCCAAGAGGAGGTTGGGAATAATTGCGTTCGATTGAATGAAAGCTCCCCTACTTCTGGCCGCAGGGTCTAAGGCACGTTCAAAGTACCTCGTTCGACCTCCCACTACGGCCTAGGTATGGATAGGTTTCGACAATTAAACACCGCGAGAATGAGCCCCTAAGATCCCAATACAAGCTCTTATGCTGCAAATGCAGGCGGGCCGAAAATCAATCGACATGGTACTCGACACTAAGTGCACCAATACAGACTACCCAGGATCTTCGACTGGGTTTCTAGAAAGT"

for n in string:
	if n == "A":
		A+=1
	elif n=="C":
		C+=1
	elif n=="G":
		G+=1
	elif n=="T":
		T+=1

ncount = [str(A), str(C), str(G), str(T)]
answer = " ".join(ncount)
print(answer)